#!/usr/bin/env node
// scripts/mergeTranslations.js
//
// Merges new translation keys into src/lib/translations.js.
// Preserves all existing keys, comments, and formatting structure.
// Idempotent — safe to run multiple times.
//
// Usage:
//   cd coachly-web
//   node scripts/mergeTranslations.js
//
// Edit the TRANSLATIONS_TO_ADD and TARGET_FILE constants below for your needs.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ─── EDIT THESE ──────────────────────────────────────────────────────────────

const TARGET_FILE = path.resolve(__dirname, "../lib/translations.js");

// Each language gets these keys. Existing keys are NEVER overwritten.
const TRANSLATIONS_TO_ADD = {
  en: {
    // UI keys
    categoryAll: "All",
    searchExercises: "Search exercises…",
    addCustom: "Add custom",
    addCustomExercise: "Add custom exercise",
    customLabel: "Custom",
    exerciseNamePlaceholder: "e.g. Cable fly",
    name: "Name",
    category: "Category",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    deleteExercise: "Delete exercise",
    deleteExerciseConfirm: "Remove",
    error: "Error",
    exercisesLoadFailed: "Could not load exercises.",
    exerciseCreateFailed: "Could not add exercise.",
    exerciseDeleteFailed: "Could not delete.",
    noExercisesFound: "No exercises found.",
    pickExercise: "Pick an exercise",
    fillWhatApplies: "Fill in whatever applies — leave the rest blank.",
    sets: "Sets",
    reps: "Reps",
    weight: "Weight",
    duration: "Duration",
    optional: "Optional",
    back: "Back",
    loading: "Loading…",
    // Exercise names
    ex_bench_press: "Bench press",
    ex_incline_bench_press: "Incline bench press",
    ex_squat: "Squat",
    ex_front_squat: "Front squat",
    ex_deadlift: "Deadlift",
    ex_romanian_deadlift: "Romanian deadlift",
    ex_overhead_press: "Overhead press",
    ex_barbell_row: "Barbell row",
    ex_dumbbell_row: "Dumbbell row",
    ex_dumbbell_curl: "Dumbbell curl",
    ex_tricep_extension: "Tricep extension",
    ex_lat_pulldown: "Lat pulldown",
    ex_pull_up: "Pull-up",
    ex_push_up: "Push-up",
    ex_lunge: "Lunge",
    ex_bulgarian_split_squat: "Bulgarian split squat",
    ex_leg_press: "Leg press",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Lateral raise",
    ex_plank: "Plank",
    ex_running: "Running",
    ex_cycling: "Cycling",
    ex_rowing: "Rowing",
    ex_swimming: "Swimming",
    ex_elliptical: "Elliptical",
    ex_jump_rope: "Jump rope",
    ex_stair_climber: "Stair climber",
    ex_walking: "Walking",
    ex_hiking: "Hiking",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Stretching",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Hip openers",
    ex_shoulder_mobility: "Shoulder mobility",
    ex_thoracic_rotation: "Thoracic rotation",
    ex_cat_cow: "Cat-cow",
    ex_pigeon_pose: "Pigeon pose",
    ex_sauna: "Sauna",
    ex_ice_bath: "Ice bath / cold plunge",
    ex_massage: "Massage",
    ex_light_walk: "Light walk",
    ex_breathwork: "Breathwork",
    ex_mobility_flow: "Mobility flow",
  },
  no: {
    categoryAll: "Alle",
    searchExercises: "Søk etter øvelser…",
    addCustom: "Legg til egen",
    addCustomExercise: "Legg til egen øvelse",
    customLabel: "Egen",
    exerciseNamePlaceholder: "f.eks. Kabel fly",
    name: "Navn",
    category: "Kategori",
    save: "Lagre",
    cancel: "Avbryt",
    delete: "Slett",
    deleteExercise: "Slett øvelse",
    deleteExerciseConfirm: "Fjern",
    error: "Feil",
    exercisesLoadFailed: "Kunne ikke laste øvelser.",
    exerciseCreateFailed: "Kunne ikke legge til øvelse.",
    exerciseDeleteFailed: "Kunne ikke slette.",
    noExercisesFound: "Ingen øvelser funnet.",
    pickExercise: "Velg en øvelse",
    fillWhatApplies: "Fyll inn det som er relevant — la resten stå tomt.",
    sets: "Sett",
    reps: "Reps",
    weight: "Vekt",
    duration: "Varighet",
    optional: "Valgfritt",
    back: "Tilbake",
    loading: "Laster…",
    ex_bench_press: "Benkpress",
    ex_incline_bench_press: "Skrå benkpress",
    ex_squat: "Knebøy",
    ex_front_squat: "Frontbøy",
    ex_deadlift: "Markløft",
    ex_romanian_deadlift: "Rumensk markløft",
    ex_overhead_press: "Stående press",
    ex_barbell_row: "Stangroing",
    ex_dumbbell_row: "Manualroing",
    ex_dumbbell_curl: "Manualcurl",
    ex_tricep_extension: "Tricepspress",
    ex_lat_pulldown: "Nedtrekk",
    ex_pull_up: "Pull-up",
    ex_push_up: "Push-up",
    ex_lunge: "Utfall",
    ex_bulgarian_split_squat: "Bulgarsk utfall",
    ex_leg_press: "Beinpress",
    ex_hip_thrust: "Hofteløft",
    ex_lateral_raise: "Sidehev",
    ex_plank: "Planke",
    ex_running: "Løping",
    ex_cycling: "Sykling",
    ex_rowing: "Roing",
    ex_swimming: "Svømming",
    ex_elliptical: "Ellipsemaskin",
    ex_jump_rope: "Hoppetau",
    ex_stair_climber: "Trappemaskin",
    ex_walking: "Gåtur",
    ex_hiking: "Fjelltur",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Tøying",
    ex_foam_rolling: "Foamrulling",
    ex_hip_openers: "Hofteåpnere",
    ex_shoulder_mobility: "Skuldermobilitet",
    ex_thoracic_rotation: "Brystvirvelrotasjon",
    ex_cat_cow: "Katt-ku",
    ex_pigeon_pose: "Duestilling",
    ex_sauna: "Badstue",
    ex_ice_bath: "Isbad / kuldebad",
    ex_massage: "Massasje",
    ex_light_walk: "Rolig gåtur",
    ex_breathwork: "Pusteøvelser",
    ex_mobility_flow: "Mobilitetsflyt",
  },
  nl: {
    categoryAll: "Alles",
    searchExercises: "Oefeningen zoeken…",
    addCustom: "Eigen toevoegen",
    addCustomExercise: "Eigen oefening toevoegen",
    customLabel: "Eigen",
    exerciseNamePlaceholder: "bv. Cable fly",
    name: "Naam",
    category: "Categorie",
    save: "Opslaan",
    cancel: "Annuleren",
    delete: "Verwijderen",
    deleteExercise: "Oefening verwijderen",
    deleteExerciseConfirm: "Verwijder",
    error: "Fout",
    exercisesLoadFailed: "Kon oefeningen niet laden.",
    exerciseCreateFailed: "Kon oefening niet toevoegen.",
    exerciseDeleteFailed: "Kon niet verwijderen.",
    noExercisesFound: "Geen oefeningen gevonden.",
    pickExercise: "Kies een oefening",
    fillWhatApplies: "Vul in wat van toepassing is — laat de rest leeg.",
    sets: "Sets",
    reps: "Reps",
    weight: "Gewicht",
    duration: "Duur",
    optional: "Optioneel",
    back: "Terug",
    loading: "Laden…",
    ex_bench_press: "Bankdrukken",
    ex_incline_bench_press: "Schuin bankdrukken",
    ex_squat: "Squat",
    ex_front_squat: "Front squat",
    ex_deadlift: "Deadlift",
    ex_romanian_deadlift: "Roemeense deadlift",
    ex_overhead_press: "Overhead press",
    ex_barbell_row: "Barbell row",
    ex_dumbbell_row: "Dumbbell row",
    ex_dumbbell_curl: "Dumbbell curl",
    ex_tricep_extension: "Triceps extensie",
    ex_lat_pulldown: "Lat pulldown",
    ex_pull_up: "Pull-up",
    ex_push_up: "Push-up",
    ex_lunge: "Lunge",
    ex_bulgarian_split_squat: "Bulgaarse split squat",
    ex_leg_press: "Beenpers",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Zijwaartse heffing",
    ex_plank: "Plank",
    ex_running: "Hardlopen",
    ex_cycling: "Fietsen",
    ex_rowing: "Roeien",
    ex_swimming: "Zwemmen",
    ex_elliptical: "Crosstrainer",
    ex_jump_rope: "Springtouw",
    ex_stair_climber: "Traploper",
    ex_walking: "Wandelen",
    ex_hiking: "Wandeltocht",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Rekken",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Heupopeners",
    ex_shoulder_mobility: "Schoudermobiliteit",
    ex_thoracic_rotation: "Borstwervelrotatie",
    ex_cat_cow: "Kat-koe",
    ex_pigeon_pose: "Duifhouding",
    ex_sauna: "Sauna",
    ex_ice_bath: "IJsbad / koud bad",
    ex_massage: "Massage",
    ex_light_walk: "Rustige wandeling",
    ex_breathwork: "Ademwerk",
    ex_mobility_flow: "Mobiliteitsflow",
  },
  fr: {
    categoryAll: "Tout",
    searchExercises: "Rechercher un exercice…",
    addCustom: "Ajouter perso",
    addCustomExercise: "Ajouter un exercice personnalisé",
    customLabel: "Perso",
    exerciseNamePlaceholder: "ex. Câble fly",
    name: "Nom",
    category: "Catégorie",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    deleteExercise: "Supprimer l'exercice",
    deleteExerciseConfirm: "Supprimer",
    error: "Erreur",
    exercisesLoadFailed: "Impossible de charger les exercices.",
    exerciseCreateFailed: "Impossible d'ajouter l'exercice.",
    exerciseDeleteFailed: "Impossible de supprimer.",
    noExercisesFound: "Aucun exercice trouvé.",
    pickExercise: "Choisir un exercice",
    fillWhatApplies: "Remplissez ce qui s'applique — laissez le reste vide.",
    sets: "Séries",
    reps: "Reps",
    weight: "Poids",
    duration: "Durée",
    optional: "Facultatif",
    back: "Retour",
    loading: "Chargement…",
    ex_bench_press: "Développé couché",
    ex_incline_bench_press: "Développé incliné",
    ex_squat: "Squat",
    ex_front_squat: "Front squat",
    ex_deadlift: "Soulevé de terre",
    ex_romanian_deadlift: "Soulevé roumain",
    ex_overhead_press: "Développé militaire",
    ex_barbell_row: "Rowing barre",
    ex_dumbbell_row: "Rowing haltère",
    ex_dumbbell_curl: "Curl haltère",
    ex_tricep_extension: "Extension triceps",
    ex_lat_pulldown: "Tirage vertical",
    ex_pull_up: "Traction",
    ex_push_up: "Pompe",
    ex_lunge: "Fente",
    ex_bulgarian_split_squat: "Fente bulgare",
    ex_leg_press: "Presse à cuisses",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Élévation latérale",
    ex_plank: "Planche",
    ex_running: "Course à pied",
    ex_cycling: "Vélo",
    ex_rowing: "Rameur",
    ex_swimming: "Natation",
    ex_elliptical: "Elliptique",
    ex_jump_rope: "Corde à sauter",
    ex_stair_climber: "Escalier",
    ex_walking: "Marche",
    ex_hiking: "Randonnée",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Étirements",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Ouvertures de hanche",
    ex_shoulder_mobility: "Mobilité d'épaule",
    ex_thoracic_rotation: "Rotation thoracique",
    ex_cat_cow: "Chat-vache",
    ex_pigeon_pose: "Posture du pigeon",
    ex_sauna: "Sauna",
    ex_ice_bath: "Bain glacé",
    ex_massage: "Massage",
    ex_light_walk: "Marche tranquille",
    ex_breathwork: "Respiration",
    ex_mobility_flow: "Flow mobilité",
  },
  de: {
    categoryAll: "Alle",
    searchExercises: "Übungen suchen…",
    addCustom: "Eigene hinzufügen",
    addCustomExercise: "Eigene Übung hinzufügen",
    customLabel: "Eigene",
    exerciseNamePlaceholder: "z. B. Kabel-Fly",
    name: "Name",
    category: "Kategorie",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    deleteExercise: "Übung löschen",
    deleteExerciseConfirm: "Entfernen",
    error: "Fehler",
    exercisesLoadFailed: "Übungen konnten nicht geladen werden.",
    exerciseCreateFailed: "Übung konnte nicht hinzugefügt werden.",
    exerciseDeleteFailed: "Konnte nicht gelöscht werden.",
    noExercisesFound: "Keine Übungen gefunden.",
    pickExercise: "Übung wählen",
    fillWhatApplies: "Trage ein, was zutrifft — lass den Rest leer.",
    sets: "Sätze",
    reps: "Wdh.",
    weight: "Gewicht",
    duration: "Dauer",
    optional: "Optional",
    back: "Zurück",
    loading: "Lädt…",
    ex_bench_press: "Bankdrücken",
    ex_incline_bench_press: "Schrägbankdrücken",
    ex_squat: "Kniebeuge",
    ex_front_squat: "Frontkniebeuge",
    ex_deadlift: "Kreuzheben",
    ex_romanian_deadlift: "Rumänisches Kreuzheben",
    ex_overhead_press: "Schulterdrücken",
    ex_barbell_row: "Langhantelrudern",
    ex_dumbbell_row: "Kurzhantelrudern",
    ex_dumbbell_curl: "Bizepscurl",
    ex_tricep_extension: "Trizepsdrücken",
    ex_lat_pulldown: "Latziehen",
    ex_pull_up: "Klimmzug",
    ex_push_up: "Liegestütz",
    ex_lunge: "Ausfallschritt",
    ex_bulgarian_split_squat: "Bulgarischer Split Squat",
    ex_leg_press: "Beinpresse",
    ex_hip_thrust: "Hip Thrust",
    ex_lateral_raise: "Seitheben",
    ex_plank: "Planke",
    ex_running: "Laufen",
    ex_cycling: "Radfahren",
    ex_rowing: "Rudern",
    ex_swimming: "Schwimmen",
    ex_elliptical: "Crosstrainer",
    ex_jump_rope: "Seilspringen",
    ex_stair_climber: "Treppensteiger",
    ex_walking: "Gehen",
    ex_hiking: "Wandern",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Dehnen",
    ex_foam_rolling: "Foam Rolling",
    ex_hip_openers: "Hüftöffner",
    ex_shoulder_mobility: "Schultermobilität",
    ex_thoracic_rotation: "Brustwirbelrotation",
    ex_cat_cow: "Katze-Kuh",
    ex_pigeon_pose: "Taubenstellung",
    ex_sauna: "Sauna",
    ex_ice_bath: "Eisbad / Kältebad",
    ex_massage: "Massage",
    ex_light_walk: "Lockerer Spaziergang",
    ex_breathwork: "Atemarbeit",
    ex_mobility_flow: "Mobilitäts-Flow",
  },
  it: {
    categoryAll: "Tutti",
    searchExercises: "Cerca esercizi…",
    addCustom: "Aggiungi personalizzato",
    addCustomExercise: "Aggiungi esercizio personalizzato",
    customLabel: "Personalizzato",
    exerciseNamePlaceholder: "es. Cable fly",
    name: "Nome",
    category: "Categoria",
    save: "Salva",
    cancel: "Annulla",
    delete: "Elimina",
    deleteExercise: "Elimina esercizio",
    deleteExerciseConfirm: "Rimuovi",
    error: "Errore",
    exercisesLoadFailed: "Impossibile caricare gli esercizi.",
    exerciseCreateFailed: "Impossibile aggiungere l'esercizio.",
    exerciseDeleteFailed: "Impossibile eliminare.",
    noExercisesFound: "Nessun esercizio trovato.",
    pickExercise: "Scegli un esercizio",
    fillWhatApplies: "Compila ciò che è pertinente — lascia il resto vuoto.",
    sets: "Serie",
    reps: "Rip.",
    weight: "Peso",
    duration: "Durata",
    optional: "Opzionale",
    back: "Indietro",
    loading: "Caricamento…",
    ex_bench_press: "Panca piana",
    ex_incline_bench_press: "Panca inclinata",
    ex_squat: "Squat",
    ex_front_squat: "Front squat",
    ex_deadlift: "Stacco",
    ex_romanian_deadlift: "Stacco rumeno",
    ex_overhead_press: "Lento avanti",
    ex_barbell_row: "Rematore con bilanciere",
    ex_dumbbell_row: "Rematore con manubrio",
    ex_dumbbell_curl: "Curl con manubri",
    ex_tricep_extension: "Estensione tricipiti",
    ex_lat_pulldown: "Lat machine",
    ex_pull_up: "Trazione",
    ex_push_up: "Piegamento",
    ex_lunge: "Affondo",
    ex_bulgarian_split_squat: "Affondo bulgaro",
    ex_leg_press: "Pressa",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Alzata laterale",
    ex_plank: "Plank",
    ex_running: "Corsa",
    ex_cycling: "Ciclismo",
    ex_rowing: "Vogatore",
    ex_swimming: "Nuoto",
    ex_elliptical: "Ellittica",
    ex_jump_rope: "Corda",
    ex_stair_climber: "Stepper",
    ex_walking: "Camminata",
    ex_hiking: "Escursionismo",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Stretching",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Apertura anche",
    ex_shoulder_mobility: "Mobilità spalle",
    ex_thoracic_rotation: "Rotazione toracica",
    ex_cat_cow: "Gatto-mucca",
    ex_pigeon_pose: "Posizione del piccione",
    ex_sauna: "Sauna",
    ex_ice_bath: "Bagno ghiacciato",
    ex_massage: "Massaggio",
    ex_light_walk: "Camminata leggera",
    ex_breathwork: "Respirazione",
    ex_mobility_flow: "Flow mobilità",
  },
  sv: {
    categoryAll: "Alla",
    searchExercises: "Sök övningar…",
    addCustom: "Lägg till egen",
    addCustomExercise: "Lägg till egen övning",
    customLabel: "Egen",
    exerciseNamePlaceholder: "t.ex. Cable fly",
    name: "Namn",
    category: "Kategori",
    save: "Spara",
    cancel: "Avbryt",
    delete: "Ta bort",
    deleteExercise: "Ta bort övning",
    deleteExerciseConfirm: "Ta bort",
    error: "Fel",
    exercisesLoadFailed: "Kunde inte ladda övningar.",
    exerciseCreateFailed: "Kunde inte lägga till övning.",
    exerciseDeleteFailed: "Kunde inte ta bort.",
    noExercisesFound: "Inga övningar hittades.",
    pickExercise: "Välj en övning",
    fillWhatApplies: "Fyll i det som gäller — lämna resten tomt.",
    sets: "Set",
    reps: "Reps",
    weight: "Vikt",
    duration: "Tid",
    optional: "Valfritt",
    back: "Tillbaka",
    loading: "Laddar…",
    ex_bench_press: "Bänkpress",
    ex_incline_bench_press: "Lutande bänkpress",
    ex_squat: "Knäböj",
    ex_front_squat: "Front squat",
    ex_deadlift: "Marklyft",
    ex_romanian_deadlift: "Rumänskt marklyft",
    ex_overhead_press: "Axelpress",
    ex_barbell_row: "Skivstångsrodd",
    ex_dumbbell_row: "Hantelrodd",
    ex_dumbbell_curl: "Hantelcurl",
    ex_tricep_extension: "Tricepspress",
    ex_lat_pulldown: "Latsdrag",
    ex_pull_up: "Pull-up",
    ex_push_up: "Armhävning",
    ex_lunge: "Utfall",
    ex_bulgarian_split_squat: "Bulgariskt utfall",
    ex_leg_press: "Benpress",
    ex_hip_thrust: "Höftlyft",
    ex_lateral_raise: "Sidlyft",
    ex_plank: "Planka",
    ex_running: "Löpning",
    ex_cycling: "Cykling",
    ex_rowing: "Rodd",
    ex_swimming: "Simning",
    ex_elliptical: "Crosstrainer",
    ex_jump_rope: "Hopprep",
    ex_stair_climber: "Trappmaskin",
    ex_walking: "Promenad",
    ex_hiking: "Vandring",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Stretching",
    ex_foam_rolling: "Foamrullning",
    ex_hip_openers: "Höftöppnare",
    ex_shoulder_mobility: "Axelrörlighet",
    ex_thoracic_rotation: "Bröstryggsrotation",
    ex_cat_cow: "Katt-ko",
    ex_pigeon_pose: "Duvposition",
    ex_sauna: "Bastu",
    ex_ice_bath: "Isbad / kallbad",
    ex_massage: "Massage",
    ex_light_walk: "Lugn promenad",
    ex_breathwork: "Andningsövningar",
    ex_mobility_flow: "Rörlighetsflöde",
  },
  da: {
    categoryAll: "Alle",
    searchExercises: "Søg øvelser…",
    addCustom: "Tilføj egen",
    addCustomExercise: "Tilføj egen øvelse",
    customLabel: "Egen",
    exerciseNamePlaceholder: "f.eks. Cable fly",
    name: "Navn",
    category: "Kategori",
    save: "Gem",
    cancel: "Annuller",
    delete: "Slet",
    deleteExercise: "Slet øvelse",
    deleteExerciseConfirm: "Fjern",
    error: "Fejl",
    exercisesLoadFailed: "Kunne ikke indlæse øvelser.",
    exerciseCreateFailed: "Kunne ikke tilføje øvelse.",
    exerciseDeleteFailed: "Kunne ikke slette.",
    noExercisesFound: "Ingen øvelser fundet.",
    pickExercise: "Vælg en øvelse",
    fillWhatApplies: "Udfyld det der passer — lad resten stå tomt.",
    sets: "Sæt",
    reps: "Reps",
    weight: "Vægt",
    duration: "Varighed",
    optional: "Valgfri",
    back: "Tilbage",
    loading: "Indlæser…",
    ex_bench_press: "Bænkpres",
    ex_incline_bench_press: "Skrå bænkpres",
    ex_squat: "Squat",
    ex_front_squat: "Front squat",
    ex_deadlift: "Dødløft",
    ex_romanian_deadlift: "Rumænsk dødløft",
    ex_overhead_press: "Skulderpres",
    ex_barbell_row: "Stangroning",
    ex_dumbbell_row: "Håndvægtroning",
    ex_dumbbell_curl: "Håndvægtcurl",
    ex_tricep_extension: "Tricepspres",
    ex_lat_pulldown: "Lat pulldown",
    ex_pull_up: "Pull-up",
    ex_push_up: "Armbøjning",
    ex_lunge: "Udfald",
    ex_bulgarian_split_squat: "Bulgarsk udfald",
    ex_leg_press: "Benpres",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Sideløft",
    ex_plank: "Planke",
    ex_running: "Løb",
    ex_cycling: "Cykling",
    ex_rowing: "Roning",
    ex_swimming: "Svømning",
    ex_elliptical: "Crosstrainer",
    ex_jump_rope: "Sjippetov",
    ex_stair_climber: "Trappemaskine",
    ex_walking: "Gåtur",
    ex_hiking: "Vandring",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Udstrækning",
    ex_foam_rolling: "Foamrulning",
    ex_hip_openers: "Hofteåbnere",
    ex_shoulder_mobility: "Skuldermobilitet",
    ex_thoracic_rotation: "Brysthvirvelrotation",
    ex_cat_cow: "Kat-ko",
    ex_pigeon_pose: "Dueposition",
    ex_sauna: "Sauna",
    ex_ice_bath: "Isbad / koldt bad",
    ex_massage: "Massage",
    ex_light_walk: "Rolig gåtur",
    ex_breathwork: "Vejrtrækningsøvelser",
    ex_mobility_flow: "Mobilitetsflow",
  },
  fi: {
    categoryAll: "Kaikki",
    searchExercises: "Hae harjoituksia…",
    addCustom: "Lisää oma",
    addCustomExercise: "Lisää oma harjoitus",
    customLabel: "Oma",
    exerciseNamePlaceholder: "esim. Cable fly",
    name: "Nimi",
    category: "Kategoria",
    save: "Tallenna",
    cancel: "Peruuta",
    delete: "Poista",
    deleteExercise: "Poista harjoitus",
    deleteExerciseConfirm: "Poista",
    error: "Virhe",
    exercisesLoadFailed: "Harjoituksia ei voitu ladata.",
    exerciseCreateFailed: "Harjoitusta ei voitu lisätä.",
    exerciseDeleteFailed: "Ei voitu poistaa.",
    noExercisesFound: "Harjoituksia ei löytynyt.",
    pickExercise: "Valitse harjoitus",
    fillWhatApplies: "Täytä mitä koskee — jätä loput tyhjäksi.",
    sets: "Sarjat",
    reps: "Toistot",
    weight: "Paino",
    duration: "Kesto",
    optional: "Valinnainen",
    back: "Takaisin",
    loading: "Ladataan…",
    ex_bench_press: "Penkkipunnerrus",
    ex_incline_bench_press: "Vinopenkki",
    ex_squat: "Kyykky",
    ex_front_squat: "Etukyykky",
    ex_deadlift: "Maastaveto",
    ex_romanian_deadlift: "Romanialainen maastaveto",
    ex_overhead_press: "Pystypunnerrus",
    ex_barbell_row: "Tankasoutu",
    ex_dumbbell_row: "Käsipainosoutu",
    ex_dumbbell_curl: "Hauiskääntö",
    ex_tricep_extension: "Ojennusliike",
    ex_lat_pulldown: "Ylätalja",
    ex_pull_up: "Leuanveto",
    ex_push_up: "Punnerrus",
    ex_lunge: "Askelkyykky",
    ex_bulgarian_split_squat: "Bulgarialainen askelkyykky",
    ex_leg_press: "Jalkaprässi",
    ex_hip_thrust: "Lantionnosto",
    ex_lateral_raise: "Sivuvipunosto",
    ex_plank: "Lankku",
    ex_running: "Juoksu",
    ex_cycling: "Pyöräily",
    ex_rowing: "Soutu",
    ex_swimming: "Uinti",
    ex_elliptical: "Crosstrainer",
    ex_jump_rope: "Hyppynaru",
    ex_stair_climber: "Porraskone",
    ex_walking: "Kävely",
    ex_hiking: "Vaellus",
    ex_hiit: "HIIT",
    ex_yoga: "Jooga",
    ex_stretching: "Venyttely",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Lonkanaukaisut",
    ex_shoulder_mobility: "Olkapäiden liikkuvuus",
    ex_thoracic_rotation: "Rintarangan kierto",
    ex_cat_cow: "Kissa-lehmä",
    ex_pigeon_pose: "Kyyhkysasento",
    ex_sauna: "Sauna",
    ex_ice_bath: "Jääkylpy",
    ex_massage: "Hieronta",
    ex_light_walk: "Kevyt kävely",
    ex_breathwork: "Hengitysharjoitukset",
    ex_mobility_flow: "Liikkuvuusvirta",
  },
  es: {
    categoryAll: "Todos",
    searchExercises: "Buscar ejercicios…",
    addCustom: "Añadir personalizado",
    addCustomExercise: "Añadir ejercicio personalizado",
    customLabel: "Personalizado",
    exerciseNamePlaceholder: "p. ej. Cable fly",
    name: "Nombre",
    category: "Categoría",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    deleteExercise: "Eliminar ejercicio",
    deleteExerciseConfirm: "Quitar",
    error: "Error",
    exercisesLoadFailed: "No se pudieron cargar los ejercicios.",
    exerciseCreateFailed: "No se pudo añadir el ejercicio.",
    exerciseDeleteFailed: "No se pudo eliminar.",
    noExercisesFound: "No se encontraron ejercicios.",
    pickExercise: "Elige un ejercicio",
    fillWhatApplies: "Rellena lo que aplique — deja el resto en blanco.",
    sets: "Series",
    reps: "Reps",
    weight: "Peso",
    duration: "Duración",
    optional: "Opcional",
    back: "Atrás",
    loading: "Cargando…",
    ex_bench_press: "Press banca",
    ex_incline_bench_press: "Press inclinado",
    ex_squat: "Sentadilla",
    ex_front_squat: "Sentadilla frontal",
    ex_deadlift: "Peso muerto",
    ex_romanian_deadlift: "Peso muerto rumano",
    ex_overhead_press: "Press militar",
    ex_barbell_row: "Remo con barra",
    ex_dumbbell_row: "Remo con mancuerna",
    ex_dumbbell_curl: "Curl con mancuerna",
    ex_tricep_extension: "Extensión de tríceps",
    ex_lat_pulldown: "Jalón al pecho",
    ex_pull_up: "Dominada",
    ex_push_up: "Flexión",
    ex_lunge: "Zancada",
    ex_bulgarian_split_squat: "Sentadilla búlgara",
    ex_leg_press: "Prensa de piernas",
    ex_hip_thrust: "Empuje de cadera",
    ex_lateral_raise: "Elevación lateral",
    ex_plank: "Plancha",
    ex_running: "Correr",
    ex_cycling: "Ciclismo",
    ex_rowing: "Remo",
    ex_swimming: "Natación",
    ex_elliptical: "Elíptica",
    ex_jump_rope: "Cuerda",
    ex_stair_climber: "Escaladora",
    ex_walking: "Caminar",
    ex_hiking: "Senderismo",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Estiramientos",
    ex_foam_rolling: "Foam roller",
    ex_hip_openers: "Apertura de caderas",
    ex_shoulder_mobility: "Movilidad de hombro",
    ex_thoracic_rotation: "Rotación torácica",
    ex_cat_cow: "Gato-vaca",
    ex_pigeon_pose: "Postura de la paloma",
    ex_sauna: "Sauna",
    ex_ice_bath: "Baño de hielo",
    ex_massage: "Masaje",
    ex_light_walk: "Paseo suave",
    ex_breathwork: "Respiración",
    ex_mobility_flow: "Flujo de movilidad",
  },
  pl: {
    categoryAll: "Wszystkie",
    searchExercises: "Szukaj ćwiczeń…",
    addCustom: "Dodaj własne",
    addCustomExercise: "Dodaj własne ćwiczenie",
    customLabel: "Własne",
    exerciseNamePlaceholder: "np. Cable fly",
    name: "Nazwa",
    category: "Kategoria",
    save: "Zapisz",
    cancel: "Anuluj",
    delete: "Usuń",
    deleteExercise: "Usuń ćwiczenie",
    deleteExerciseConfirm: "Usuń",
    error: "Błąd",
    exercisesLoadFailed: "Nie udało się załadować ćwiczeń.",
    exerciseCreateFailed: "Nie udało się dodać ćwiczenia.",
    exerciseDeleteFailed: "Nie udało się usunąć.",
    noExercisesFound: "Nie znaleziono ćwiczeń.",
    pickExercise: "Wybierz ćwiczenie",
    fillWhatApplies: "Wpisz to, co dotyczy — resztę zostaw pustą.",
    sets: "Serie",
    reps: "Powt.",
    weight: "Ciężar",
    duration: "Czas",
    optional: "Opcjonalne",
    back: "Wstecz",
    loading: "Ładowanie…",
    ex_bench_press: "Wyciskanie sztangi leżąc",
    ex_incline_bench_press: "Wyciskanie skos dodatni",
    ex_squat: "Przysiad",
    ex_front_squat: "Przysiad przedni",
    ex_deadlift: "Martwy ciąg",
    ex_romanian_deadlift: "Rumuński martwy ciąg",
    ex_overhead_press: "Wyciskanie żołnierskie",
    ex_barbell_row: "Wiosłowanie sztangą",
    ex_dumbbell_row: "Wiosłowanie hantlą",
    ex_dumbbell_curl: "Uginanie z hantlami",
    ex_tricep_extension: "Wyciskanie francuskie",
    ex_lat_pulldown: "Ściąganie drążka",
    ex_pull_up: "Podciąganie",
    ex_push_up: "Pompka",
    ex_lunge: "Wykrok",
    ex_bulgarian_split_squat: "Bułgarski przysiad",
    ex_leg_press: "Wyciskanie nogami",
    ex_hip_thrust: "Hip thrust",
    ex_lateral_raise: "Unoszenie bokiem",
    ex_plank: "Deska",
    ex_running: "Bieganie",
    ex_cycling: "Jazda na rowerze",
    ex_rowing: "Wioślarz",
    ex_swimming: "Pływanie",
    ex_elliptical: "Orbitrek",
    ex_jump_rope: "Skakanka",
    ex_stair_climber: "Steper",
    ex_walking: "Spacer",
    ex_hiking: "Wędrówka",
    ex_hiit: "HIIT",
    ex_yoga: "Joga",
    ex_stretching: "Rozciąganie",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Otwieranie bioder",
    ex_shoulder_mobility: "Mobilność barków",
    ex_thoracic_rotation: "Rotacja piersiowa",
    ex_cat_cow: "Kot-krowa",
    ex_pigeon_pose: "Pozycja gołębia",
    ex_sauna: "Sauna",
    ex_ice_bath: "Lodowa kąpiel",
    ex_massage: "Masaż",
    ex_light_walk: "Lekki spacer",
    ex_breathwork: "Ćwiczenia oddechowe",
    ex_mobility_flow: "Mobilność – flow",
  },
  pt: {
    categoryAll: "Todos",
    searchExercises: "Pesquisar exercícios…",
    addCustom: "Adicionar personalizado",
    addCustomExercise: "Adicionar exercício personalizado",
    customLabel: "Personalizado",
    exerciseNamePlaceholder: "ex. Cable fly",
    name: "Nome",
    category: "Categoria",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Apagar",
    deleteExercise: "Apagar exercício",
    deleteExerciseConfirm: "Remover",
    error: "Erro",
    exercisesLoadFailed: "Não foi possível carregar os exercícios.",
    exerciseCreateFailed: "Não foi possível adicionar o exercício.",
    exerciseDeleteFailed: "Não foi possível apagar.",
    noExercisesFound: "Nenhum exercício encontrado.",
    pickExercise: "Escolhe um exercício",
    fillWhatApplies: "Preenche o que se aplica — deixa o resto em branco.",
    sets: "Séries",
    reps: "Reps",
    weight: "Peso",
    duration: "Duração",
    optional: "Opcional",
    back: "Voltar",
    loading: "A carregar…",
    ex_bench_press: "Supino",
    ex_incline_bench_press: "Supino inclinado",
    ex_squat: "Agachamento",
    ex_front_squat: "Agachamento frontal",
    ex_deadlift: "Levantamento terra",
    ex_romanian_deadlift: "Levantamento terra romeno",
    ex_overhead_press: "Desenvolvimento",
    ex_barbell_row: "Remada com barra",
    ex_dumbbell_row: "Remada com halter",
    ex_dumbbell_curl: "Rosca com halter",
    ex_tricep_extension: "Extensão tríceps",
    ex_lat_pulldown: "Puxada alta",
    ex_pull_up: "Barra fixa",
    ex_push_up: "Flexão",
    ex_lunge: "Afundo",
    ex_bulgarian_split_squat: "Afundo búlgaro",
    ex_leg_press: "Leg press",
    ex_hip_thrust: "Elevação de quadril",
    ex_lateral_raise: "Elevação lateral",
    ex_plank: "Prancha",
    ex_running: "Corrida",
    ex_cycling: "Ciclismo",
    ex_rowing: "Remo",
    ex_swimming: "Natação",
    ex_elliptical: "Elíptico",
    ex_jump_rope: "Corda",
    ex_stair_climber: "Escada",
    ex_walking: "Caminhada",
    ex_hiking: "Trilha",
    ex_hiit: "HIIT",
    ex_yoga: "Yoga",
    ex_stretching: "Alongamento",
    ex_foam_rolling: "Foam rolling",
    ex_hip_openers: "Abertura de quadril",
    ex_shoulder_mobility: "Mobilidade do ombro",
    ex_thoracic_rotation: "Rotação torácica",
    ex_cat_cow: "Gato-vaca",
    ex_pigeon_pose: "Postura do pombo",
    ex_sauna: "Sauna",
    ex_ice_bath: "Banho gelado",
    ex_massage: "Massagem",
    ex_light_walk: "Caminhada leve",
    ex_breathwork: "Respiração",
    ex_mobility_flow: "Fluxo de mobilidade",
  },
};

// ─── MERGE LOGIC (don't edit below) ──────────────────────────────────────────

function escapeForRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function indentLines(s, indent) {
  return s
    .split("\n")
    .map((line, i) => (i === 0 ? line : indent + line))
    .join("\n");
}

function formatValue(v) {
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v))
    return "[\n" + v.map((x) => `      ${JSON.stringify(x)}`).join(",\n") + "\n    ]";
  return JSON.stringify(v);
}

function mergeIntoLanguageBlock(content, langCode, additions) {
  // Match: "langCode": { ... }  (handles single or double quotes)
  const blockRegex = new RegExp(
    `(["']${escapeForRegex(langCode)}["']\\s*:\\s*\\{)([\\s\\S]*?)(\\n\\s*\\})`,
    "m"
  );
  const match = content.match(blockRegex);
  if (!match) {
    console.warn(`  ⚠ Language block "${langCode}" not found — skipping.`);
    return { content, added: 0, skipped: 0, missing: true };
  }

  const [full, openBrace, body, closeBrace] = match;
  let added = 0;
  let skipped = 0;
  const newLines = [];

  for (const [key, value] of Object.entries(additions)) {
    // Check whether the key is already present in this language block.
    const keyRegex = new RegExp(`["']${escapeForRegex(key)}["']\\s*:`);
    if (keyRegex.test(body)) {
      skipped++;
      continue;
    }
    newLines.push(`    ${JSON.stringify(key)}: ${formatValue(value)}`);
    added++;
  }

  if (added === 0) return { content, added: 0, skipped, missing: false };

  // Detect existing trailing comma style from the body
  const trimmed = body.replace(/\s+$/, "");
  const hasTrailingComma = trimmed.endsWith(",");
  const separator = hasTrailingComma ? "" : ",";

  const insert = "\n" + newLines.join(",\n") + (hasTrailingComma ? "," : "");
  const newBody = trimmed + separator + insert;

  const newContent = content.replace(full, openBrace + newBody + closeBrace);
  return { content: newContent, added, skipped, missing: false };
}

function main() {
  if (!fs.existsSync(TARGET_FILE)) {
    console.error(`Target file not found: ${TARGET_FILE}`);
    process.exit(1);
  }

  const original = fs.readFileSync(TARGET_FILE, "utf8");
  const backupPath = TARGET_FILE + ".backup-" + Date.now();
  fs.writeFileSync(backupPath, original);
  console.log(`Backup written: ${path.basename(backupPath)}`);

  let content = original;
  let totalAdded = 0;
  let totalSkipped = 0;
  let missingLangs = [];

  console.log("\nMerging:");
  for (const [lang, additions] of Object.entries(TRANSLATIONS_TO_ADD)) {
    const result = mergeIntoLanguageBlock(content, lang, additions);
    content = result.content;
    if (result.missing) {
      missingLangs.push(lang);
    } else {
      console.log(
        `  ${lang}: +${result.added} added, ${result.skipped} already present`
      );
      totalAdded += result.added;
      totalSkipped += result.skipped;
    }
  }

  if (content === original) {
    console.log("\nNo changes needed — all keys already present.");
    fs.unlinkSync(backupPath);
    return;
  }

  fs.writeFileSync(TARGET_FILE, content);

  console.log(`\n✓ ${path.basename(TARGET_FILE)} updated.`);
  console.log(`  Total added: ${totalAdded}`);
  console.log(`  Total skipped (already present): ${totalSkipped}`);
  if (missingLangs.length) {
    console.log(`  ⚠ Missing language blocks: ${missingLangs.join(", ")}`);
  }
  console.log(`\nIf anything looks wrong, restore with:`);
  console.log(`  mv "${backupPath}" "${TARGET_FILE}"`);
}

main();